M48
; DRILL file {KiCad 9.0.5} date 2026-04-12T00:32:08-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-12T00:32:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C1.500
%
G90
G05
T1
X74.09Y-58.19
X79.87Y-58.19
T2
X48.8Y-55.245
X51.8Y-55.245
T3
X-5.076Y-92.68
X-4.06Y-87.6
X-3.044Y-92.68
T4
X0.507Y-85.562
X8.286Y-93.34
T5
X32.495Y-60.92
X62.635Y-54.26
M30
