name: Build
on:
  push:
    branches: [main]
    paths:
        - simulator/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
            node-version: 16.x
      
      - name: Build simulator
        run: |
          cd simulator
          npm run build
