name: Site
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zine
        uses: kristoff-it/setup-zine@v1
        with:
          version: 0.12.0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
            node-version: 20.x

      - name: Build manual
        working-directory: manual
        run: zine release

      - name: Build simulator
        working-directory: simulator
        run: |
          npm ci
          npm run build
          touch dist/.nojekyll

      - name: Copy simulator to site
        run: cp -a simulator/dist/* manual/release/simulator

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: "simulator/dist/"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
